ガイド追加: @click で商品を選択する (#108)
vuejs-jp/handson-vue3 pull request #111
Opened 2022-01-02 07:46 UTC by totocalcio

「@click で商品を選択する」章に「キー修飾子を使ったキーボードイベントの使い方」を追加しました。

2022-01-03 09:35 UTC, k-miyake requested changes
@totocalcio 全体的には良いと思いました。細かいところでいくつかコメントしましたのでご確認下さい:pray:

2022-01-03 09:35 UTC, k-miyake commented on docs/event.md
> +`keyup` イベントにキーコード `enter` を設定し、alert メソッドを記述しました。input タグにフォーカスし、キーボードの Enter を押すと alert メソッドが実行されます。また、`click` イベントと同様に `keyup` イベントも省略して記述できます。
`省略して` の部分で `v-on` を省略できることを明示的に書いた方が良いと思います。

2022-01-03 09:35 UTC, k-miyake commented on docs/event.md
> +しかし、このままですと要素を選択肢して `Enter` を押しても何も反応しません。`div` タグが静的 HTML 要素でありキーボードによるアクセスができないためです。そのため `div` タグへのキーボードのアクセスが可能となるようにアクションを追加します。
`選択肢して` -> `選択して` ですかね？

2022-01-07 06:55 UTC, 448jp requested changes

2022-01-07 06:55 UTC, 448jp commented on docs/event.md
> +マウスクリックではなくキーボードの操作で商品の選択を行うことがあるかもしれません。そのような時には `v-on` ディレクティブに対してキー修飾子を追加することで、キーボードイベントを使用することができます。
「～することで」という言い方は冗長なため、「追加すると、」に言い換えるとよりシンプルになります。

同様に、「～することができます。」も「使用できます。」に言い換えられます。

2022-01-07 06:55 UTC, 448jp commented on docs/event.md
> +`v-on` ディレクティブにキーボードイベントを追加するためには `keyup` イベントを設定します。`keyup` イベントには使用したいキーコードをつなげて、実行したい処理を記述します。
`keyup` イベントにキーコードをつなげるときには `.` （ドット）が必要であることにも触れたほうがよさそうです。

2022-01-07 06:55 UTC, 448jp commented on docs/event.md
> +しかし、このままですと要素を選択肢して `Enter` を押しても何も反応しません。`div` タグが静的 HTML 要素でありキーボードによるアクセスができないためです。そのため `div` タグへのキーボードのアクセスが可能となるようにアクションを追加します。
「アクションを追加」という言い回しが一般的ではなさそうに感じるので、シンプルに「`tabindex` 属性を追加します。」ではどうでしょうか？

2022-01-08 06:10 UTC, k-miyake reviewed
自分が指摘させていただいた事項が修正されていることを確認しました。

2022-01-10 12:10 UTC, 448jp approved these changes
バッチリ修正されていることを確認しました 😄

2022-01-10 12:59 UTC, k-miyake approved these changes
LGTMです！

2022-01-10 13:04 UTC, merged