computedの違い (#107)
vuejs-jp/handson-vue3 pull request #117
Opened 2022-02-16 13:06 UTC by totocalcio

computedとの違いをガイドに追加しました

2022-02-17 01:34 UTC, 448jp reviewed
ざっとレビューしてみました！

2022-02-17 01:34 UTC, 448jp commented on docs/methods.md
> +確認を行うための準備として、`methods` オプションで商品数を表示する関数を定義していきます。
「～を行う」は冗長になりがちなので省略するとよさそうです。

```suggestion
確認の準備として、`methods` オプションで商品数を表示する関数を定義していきます。
```

2022-02-17 01:34 UTC, 448jp commented on docs/methods.md
> +  売り切れです<button @click="stockItem(item)">入荷</button>
buttonタグでtype属性を省略すると`submit`扱いになるので、属性を指定したほうがよさそうです。

```suggestion
  売り切れです<button type="button" @click="stockItem(item)">入荷</button>
```

2022-02-17 01:34 UTC, 448jp commented on docs/methods.md
> +     *
ここってコメントなしで大丈夫でしょうか？

2022-02-17 01:34 UTC, 448jp commented on docs/methods.md
> +  <div>商品数：{{ stockQuantity() }}</div>
methodsも引数を使わない場合は`()`を省略できるので、以下でどうでしょうか？

```suggestion
  <div>商品数：{{ stockQuantity }}</div>
```

2022-02-17 01:34 UTC, 448jp commented on docs/methods.md
> +商品数を表すプロパティとして `goods` を定義しました。次に、`computed` オプションに `goods` の値を扱う関数を定義していきます。
ここであえてgoodsプロパティを定義しているのは、computedからはdataオプションの値を直接変更できないことを明示するためでしょうか？

本来のcomputedの説明とすれば、以下のように書くのがシンプルになるかな、と……。どこまでdataオプションの値を変更できない点にフォーカスを置くか、になると思いますが……。

```js
goods() {
    return this.items.filter(item => item.soldOut === false ).length
}

2022-02-17 01:34 UTC, 448jp commented on docs/methods.md
> +大きな違いとして `computed` オプションにはキャッシュ機能があるため、リロードのタイミングが異なります。
「リロード」という言葉がページ自体の再読み込みを連想させるので、別の言葉に置き換えたいです。「値の更新タイミング」とかでしょうか。

2022-02-17 05:28 UTC, k-miyake requested changes
1箇所コメントしました。

2022-02-17 05:28 UTC, k-miyake commented on docs/methods.md
> +ここに[v-else や v-else-if の使い方](http://localhost:8081/v-if.html#dom-%E8%A6%81%E7%B4%A0%E3%81%AB-v-if-%E3%82%92%E8%BF%BD%E5%8A%A0)のコードを参考に、入荷のボタンを追加してみます。
ホストを `https://handson.vuejs-jp.org` に変更して下さい

2022-02-17 16:32 UTC, nalpan reviewed
@totocalcio 
作成ありがとうございます！
他の章では出てこない単語などについてコメントしました。
説明が必要な語句はできるだけ控えるとターゲット層（初学者、デザイナー）には混乱をうみにくいかな？と思いました 🙇

2022-02-17 16:32 UTC, nalpan commented on docs/methods.md
> +`methods` オプションに定義されていた `getDate()` 関数では、入荷ボタンをクリックすると更新されましたが、`computed` オプションに定義した `getDateComputed` プロパティは更新されません。こちらは `computed` オプションのリロードのタイミングは Vue インスタンスの状態が更新された場合であり、リアクティブなデータを扱っていないと自動的にリ
@448jp さんも書かれていますが、リロードのタイミング -> 値の更新タイミング などが良いかと思います。
「インスタンス」という言葉も悩ましいですね…ここでも `data` が更新された場合、などでも良いような気がします。

2022-02-21 01:00 UTC, 448jp reviewed
ありがとうございます、かなり改善されたと思います！

2022-02-21 01:00 UTC, 448jp commented on docs/methods.md
> +`methods` オプションに定義されていた `getDate()` 関数では、入荷ボタンをクリックすると更新されましたが、`computed` オプションに定義した `getDateComputed` プロパティは更新されません。こちらは `computed` オプションの値の更新タイミングが `data` が更新された場合であり、`data` を扱っていないと自動的に値が更新されないことが
更新タイミングとキャッシュの有無はトレードオフだと思いますので、キャッシュが効いていることによるメリットも述べておかないとmethodsのほうが便利に感じてしまいそうかな、と感じました。公式ドキュメントでもキャッシュのメリットは述べられているので、同じようなことが言えればいいと思います。

2022-02-21 01:38 UTC, nalpan commented
@totocalcio 
ありがとうございます！
私の分はLGTMです 🙇

2022-02-21 01:38 UTC, nalpan approved these changes
@totocalcio
ありがとうございます！
私の分はLGTMです 🙇

2022-02-21 02:25 UTC, k-miyake approved these changes
私の分も修正されたことを確認できました。

2022-02-22 00:10 UTC, 448jp approved these changes
LGTMです🎉

2022-02-22 00:10 UTC, merged