ガイド追加: v-if で表示・非表示を切り替える #105
vuejs-jp/handson-vue3 pull request #121
Opened 2022-02-21 10:18 UTC by happylifetaka

「v-if で表示・非表示を切り替える」章に以下を追加しました。

- v-showとの違い
- v-forとの併用ができない

2022-02-21 11:52 UTC, k-miyake requested changes
1箇所コメントしています。

その他全体的な言い回しは @448jp レビューお願いします:pray:

2022-02-21 11:52 UTC, k-miyake commented on docs/v-if.md
> +以下のように、表示・非表示を制御したい DOM 要素に `v-show` を追加します。`v-if` の値が `true` の場合は表示され、 `false` の場合は表示されません。
```suggestion
以下のように、表示・非表示を制御したい DOM 要素に `v-show` を追加します。`v-show` の値が `true` の場合は表示され、 `false` の場合は表示されません。
```
ここは `v-show` の値がですよね？

2022-02-21 17:37 UTC, happylifetaka commented on docs/v-if.md
> +以下のように、表示・非表示を制御したい DOM 要素に `v-show` を追加します。`v-if` の値が `true` の場合は表示され、 `false` の場合は表示されません。
v-showですね。直し忘れすいません。🙇‍♂️

2022-02-21 17:39 UTC, happylifetaka commented on docs/v-if.md
> +以下のように、表示・非表示を制御したい DOM 要素に `v-show` を追加します。`v-if` の値が `true` の場合は表示され、 `false` の場合は表示されません。
修正いたしました。

2022-02-22 00:19 UTC, 448jp reviewed
主に日本語面でレビューしてみました。

2022-02-22 00:19 UTC, 448jp commented on docs/v-if.md
> +以下のように、表示・非表示を制御したい DOM 要素に `v-show` を追加します。`v-show` の値が `true` の場合は表示され、 `false` の場合は表示されません。
余分な改行が入っていましたので、削除でお願いします。

```suggestion
`v-if` に似た `v-show` というディレクティブが用意されています。以下のように、表示・非表示を制御したい DOM 要素に `v-show` を追加します。`v-show` の値が `true` の場合は表示され、 `false` の場合は表示されません。
```

2022-02-22 00:19 UTC, 448jp commented on docs/v-if.md
> +ただし、 `v-show` ディレクティブの場合、 `v-if` が DOM 要素ごと削除しているのに対して、 スタイル属性に `display:none` を付与して非表示にしています。
主語「`v-show` ディレクティブの場合（は）」と、述語「非表示にしています。」が離れており意味を理解しづらいので、以下のように改善してみてはどうでしょうか？

```suggestion
一見 `v-if` と同じように思えますが、`v-if` が DOM 要素ごと削除しているのに対して、`v-show` は style 属性の値に `display:none;` を付与して非表示にしています。
```

2022-02-22 00:19 UTC, 448jp commented on docs/v-if.md
> + `v-if` は、表示の切り替えのコストが高く、 `v-show` は、それより高い初期描画のコストが高いです。そのため、頻繁に表示の切り替えを行うのであれば、  `v-show` を使用し、それ以外では `v-if` の使用を推奨します。
```suggestion
`v-if` は表示を切り替えるコストが高く、 `v-show` は初期描画のコストが高いです。そのため、頻繁に表示を切り替えるのであれば `v-show` を使い、それ以外では `v-if` を使うとよいでしょう。
```

2022-02-22 00:19 UTC, 448jp commented on docs/v-if.md
> +`v-show` は `<template>` 要素に使用できないことに気をつけましょう。また、 `v-else` や `v-else-if` も使用できません。
```suggestion
`v-show` は `<template>` 要素に使えないことに気をつけましょう。また、 `v-else` や `v-else-if` も使えません。
```

2022-02-22 00:19 UTC, 448jp commented on docs/v-if.md
> +以下の例のように、別の要素に分けることを推奨します。
```suggestion
`v-if` と `v-for` を同時に使うことは推奨されていません。なぜなら、同じ要素において `v-for` は `v-if` より優先度が高く `v-if` の評価に関わらず `v-for` の表示処理が行われるためです。以下の例のように、別の要素に分けることを推奨します。
```

2022-02-22 03:12 UTC, k-miyake approved these changes
修正が確認できましたので LGTM です！

2022-02-22 03:59 UTC, merged