[ガイドの create-vue 対応] methods で価格にカンマを入れる
vuejs-jp/handson-vue3 pull request #135
Opened 2022-05-28 09:27 UTC by totocalcio

#131

2022-06-21 04:35 UTC, kazupon requested changes
レビュー 👀 しました。
算出プロパティ周り、コメント (suggestion) した内容でお願いします。

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +Vue.js には関数の他に、算出プロパティを扱う `computed` プロパティがあります。この違いについて説明していきます。
Vue の Composition API で提供される `computed` をそのまま明記した方が、以降で説明しやすくなるかと思います。

```suggestion
Vue.js には関数の他に、算出プロパティがあります。算出プロパティは `computed` を使って関数と同様に定義します。以降、関数との違いについて説明していきます。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +まず、関数と `computed` プロパティの違いを知るために、`template` でどのように扱うのかをそれぞれ確認してみましょう。
```suggestion
まず、関数と算出プロパティの違いを知るために、`template` でどのように扱うのかをそれぞれ確認してみましょう。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +#### `computed` プロパティで商品数を表示する
```suggestion
#### 算出プロパティで商品数を表示する
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +`computed` プロパティは関数と違って算出プロパティです。そのため、定義した `computed` プロパティを `template` で使う際には `()` は不要です。
```suggestion
関数で定義したものは JavaScript のまさに関数ですが、`computed` を使うことで、JavaScript のオブジェクトで定義したプロパティと同じように扱うことができる算出プロパティとして定義されます。そのため、`computed` で定義された算出プロパティを `template` で使う際には `()` は不要です。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +#### 関数と `computed` プロパティの違い
```suggestion
#### 関数と算出プロパティの違い
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +関数でも `computed` プロパティでも最終的に同じ値を取得することが可能ですが、2 つの違いはどこにあるのでしょうか。
```suggestion
関数でも算出プロパティでも最終的に同じ値を取得することが可能ですが、2 つの違いはどこにあるのでしょうか。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +- `computed` プロパティ : `items` が更新された時
```suggestion
- 算出プロパティ  : `items` が更新された時
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +次に `computed` プロパティに現在時刻を取得する処理を追加してみましょう。
```suggestion
次に `computed` で定義している算出プロパティのロジックに、現在時刻を取得する処理を追加してみましょう。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +関数で定義されていた `getDate()` では、入荷ボタンをクリックすると更新されましたが、`computed` プロパティに定義した `getDateComputed` は更新されません。こちらは `computed` プロパティの値の更新タイミングが `items` が更新された場合であり、`items` を扱っていないと自動的に値が更新されないことが理由です。
```suggestion
関数で定義されていた `getDate()` では、入荷ボタンをクリックすると更新されましたが、`computed` を使って定義された算出プロパティ `getDateComputed` は更新されません。この算出プロパティの値の更新タイミングは `items` が更新された場合であり、`items` を扱っていないと自動的に値が更新されないことが理由です。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
>  ## 算出プロパティ `computed` との違い
ここでは、以下のようにタイトル付けしておくと以降、説明しやすくなるかとおもます。

```
## 算出プロパティとの違い
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +関数で商品数を表示しましたが、`computed` プロパティでも商品数を表示してみます。
```suggestion
関数で商品数を表示しましたが、`computed` を使って算出プロパティでも商品数を表示することができます。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +以上のように、関数と `computed` プロパティでは更新のタイミングが違うので注意が必要です。
```suggestion
以上のように、関数と算出プロパティでは更新のタイミングが違うので注意が必要です。
```

2022-06-21 04:35 UTC, kazupon commented on docs/methods.md
> +毎回自動的に更新がされるため、関数の方が便利そうです。しかし、これには注意が必要です。例えば、巨大な配列をループして多くの計算が必要な処理があったとします。関数で定義した場合 `template` が更新される度に、このループ処理が実行されてしまいます。しかし、`computed` プロパティで定義していた場合はキャッシュが効いているので実行されません。
```suggestion
毎回自動的に更新がされるため、関数の方が便利そうです。しかし、これには注意が必要です。例えば、巨大な配列をループして多くの計算が必要な処理があったとします。関数で定義した場合 `template` が更新される度に、このループ処理が実行されてしまいます。しかし、算出プロパティで定義していた場合はキャッシュが効いているので実行されません。
```

2022-06-25 08:27 UTC, kazupon approved these changes
確認しました。
いいですね！

2022-06-25 21:47 UTC, k-miyake approved these changes
修正を確認できましたのでマージします。
@kazupon 協力ありがとうございました。

2022-06-25 21:48 UTC, k-miyake approved these changes

2022-06-25 21:49 UTC, merged