tree図を追加
vuejs-jp/handson-vue3 pull request #184
Opened 2023-04-26 09:12 UTC by watasan1012

[[ハンズオン資料の最初にフォルダ構成をtree上で表示する#96](https://github.com/vuejs-jp/vuefes-2023/issues/96)](https://github.com/orgs/vuejs-jp/projects/3/views/9?pane=issue&itemId=22994552)

[handson側issues](https://github.com/vuejs-jp/handson-vue3/issues/183)

に対応しました。

2023-05-01 08:09 UTC, k-miyake requested changes
@watasan1012 @harop 一部コメントをしましたのでご確認ください。

2023-05-01 08:09 UTC, k-miyake commented on docs/create.md
> +    ```
@harop @watasan1012 コードブロックの部分ですが、理由はわからないのですが、スペース4つだとなぜか ``` がレンダリングされてしまいます。軽く試したところ、コードブロックのインデントを全てスペース2にすると治るみたいです。お手数ですが修正をお願いします。

2023-05-01 08:09 UTC, k-miyake commented on docs/create.md
> +これらのファイルが create-vue コマンドで作成されます。
@watasan1012 @harop create-vue のところは文章中のコマンドがわかりやすくなるよう `create-vue` のような表記にした方が良さそうです。

2023-05-01 09:47 UTC, watasan1012 commented on docs/create.md
> +これらのファイルが create-vue コマンドで作成されます。
承知しました。修正します！

2023-05-02 08:12 UTC, k-miyake commented on docs/create.md
> +    ```
@watasan1012  こちらは修正されていることを確認できました。

2023-05-04 05:58 UTC, k-miyake commented on docs/create.md
> +これらのファイルが create-vue で作成されます。
```suggestion
これらのファイルが `create-vue` で作成されます。
```

2023-05-04 06:00 UTC, k-miyake approved these changes

2023-05-04 06:00 UTC, merged